## Data example

In [1]:
import pandas as pd
import sqlite3
from pathlib import Path

C:\Users\grace\AppData\Local\Temp\ipykernel_20328\2870000203.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
conn = sqlite3.connect(":memory:")

data_dir = Path("data")

csv_files = [
    "cart_data.csv",
    "cart_item_data.csv",
    "category_data.csv",
    "data.csv",
    "order_data.csv",
    "order_items_data.csv",
    "payment_data.csv",
    "product_data.csv",
    "review_data.csv",
    "shipping_data.csv",
    "user_data.csv",
]

for file in csv_files:
    table_name = file.replace(".csv", "")
    df = pd.read_csv(data_dir / file)
    df.to_sql(table_name, conn, index=False, if_exists="replace")
    print(f"Loaded {file} as table: {table_name}")

Loaded cart_data.csv as table: cart_data
Loaded cart_item_data.csv as table: cart_item_data
Loaded category_data.csv as table: category_data
Loaded data.csv as table: data
Loaded order_data.csv as table: order_data
Loaded order_items_data.csv as table: order_items_data
Loaded payment_data.csv as table: payment_data
Loaded product_data.csv as table: product_data
Loaded review_data.csv as table: review_data
Loaded shipping_data.csv as table: shipping_data
Loaded user_data.csv as table: user_data

In [5]:
user_data_test = """
SELECT *
FROM user_data
LIMIT 10;
"""

In [6]:
pd.read_sql_query(user_data_test, conn)

,user_id,username,email,password,address,phone_number
0,1,johndoe,johndoe@example.com,pass123,123 Main St,123-456-7890
1,2,janesmith,janesmith@example.com,pass456,456 Elm St,987-654-3210
2,3,maryjones,maryjones@example.com,pass789,789 Oak St,555-123-4567
3,4,robertbrown,robertbrown@example.com,passabc,321 Pine St,111-222-3333
4,5,sarahwilson,sarahwilson@example.com,passxyz,567 Maple St,444-555-6666
5,6,michaellee,michaellee@example.com,pass456,890 Cedar St,777-888-9999
6,7,lisawilliams,lisawilliams@example.com,pass789,432 Birch St,222-333-4444
7,8,chrisharris,chrisharris@example.com,pass123,876 Walnut St,666-777-8888
8,9,emilythompson,emilythompson@example.com,passabc,543 Oak St,999-000-1111
9,10,davidmartinez,davidmartinez@example.com,passxyz,987 Elm St,333-444-5555

In [8]:
cart_data_test = """
SELECT *
FROM cart_data
LIMIT 10;
"""

In [9]:
pd.read_sql_query(cart_data_test, conn)

   cart_id  user_id
0        1        1
1        2        2
2        3        3
3        4        4
4        5        5
5        6        6
6        7        7
7        8        8
8        9        9
9       10       10

In [11]:
cart_item_data_test = """
SELECT *
FROM cart_item_data
LIMIT 10;
"""

In [12]:
pd.read_sql_query(cart_item_data_test, conn)

   cart_item_id  cart_id  product_id  quantity
0             1        1           1         1
1             2        1           2         2
2             3        2           3         1
3             4        2           4         3
4             5        3           5         2
5             6        3           6         1
6             7        4           7         3
7             8        4           8         1
8             9        5           9         2
9            10        5          10         1

In [13]:
category_data_test = """
SELECT *
FROM category_data
LIMIT 10;
"""

pd.read_sql_query(category_data_test, conn)

   category_id             category_name
0            1               Electronics
1            2                     Books
2            3                  Clothing
3            4            Home & Kitchen
4            5              Toys & Games
5            6    Beauty & Personal Care
6            7        Health & Household
7            8         Sports & Outdoors
8            9                Automotive
9           10  Tools & Home Improvement

In [14]:
data_test = """
SELECT *
FROM data
LIMIT 10;
"""

pd.read_sql_query(data_test, conn)

,user_id,username,email,password,address,phone_number
0,1,johndoe,johndoe@example.com,pass123,123 Main St,123-456-7890
1,2,janesmith,janesmith@example.com,pass456,456 Elm St,987-654-3210
2,order_id,user_id,order_date,total_amount,None,None
3,1,1,2021-01-01,100.00,None,None
4,2,2,2021-02-01,200.00,None,None
5,order_item_id,order_id,product_id,quantity,unit_price,None
6,1,1,1,2,50.00,None
7,2,1,2,1,25.00,None
8,3,2,3,3,30.00,None
9,product_id,product_name,description,price,category_id,None

In [15]:
order_data_test = """
SELECT *
FROM order_data
LIMIT 10;
"""

pd.read_sql_query(order_data_test, conn)

   order_id  user_id  order_date  total_amount
0         1        1  2021-01-05         100.0
1         2        2  2021-02-10          75.0
2         3        3  2021-03-15         120.0
3         4        4  2021-04-20         155.0
4         5        5  2021-05-25          90.0
5         6        6  2021-06-30          80.0
6         7        7  2021-07-05         125.0
7         8        8  2021-08-10         150.0
8         9        9  2021-09-15          95.0
9        10       10  2021-10-20          70.0

In [16]:
order_items_data_test = """
SELECT *
FROM order_items_data
LIMIT 10;
"""

pd.read_sql_query(order_items_data_test, conn)

   order_item_id  order_id  product_id  quantity  unit_price
0              1         1           1         2        50.0
1              2         1           2         1        25.0
2              3         2           3         3        30.0
3              4         2           4         1        15.0
4              5         3           5         2        20.0
5              6         3           6         1        10.0
6              7         4           7         3        35.0
7              8         4           8         1        40.0
8              9         5           9         2        30.0
9             10         5          10         1        25.0

In [17]:
payment_data_test = """
SELECT *
FROM payment_data
LIMIT 10;
"""

pd.read_sql_query(payment_data_test, conn)

   payment_id  order_id payment_date payment_method  amount
0           1         1   2021-01-02    Credit Card   100.0
1           2         2   2021-02-02         PayPal   200.0
2           3         3   2021-03-02    Credit Card   150.0
3           4         4   2021-04-02         PayPal   175.0
4           5         5   2021-05-02    Credit Card   120.0
5           6         6   2021-06-02         PayPal    90.0
6           7         7   2021-07-02    Credit Card   135.0
7           8         8   2021-08-02         PayPal   160.0
8           9         9   2021-09-02    Credit Card   105.0
9          10        10   2021-10-02         PayPal   140.0

In [18]:
product_data_test = """
SELECT *
FROM product_data
LIMIT 10;
"""

pd.read_sql_query(product_data_test, conn)

,product_id,product_name,description,price,category_id
0,1,Smartphone X,The Smartphone X is a powerful and feature-ric...,500.0,1
1,2,Wireless Headphones,Experience the freedom of wireless audio with ...,150.0,1
2,3,Laptop Pro,The Laptop Pro is a sleek and powerful device ...,1200.0,2
3,4,Smart TV,Transform your living room into an entertainme...,800.0,2
4,5,Running Shoes,Get ready to hit the road with these lightweig...,100.0,3
5,6,Designer Dress,Make a statement with this elegant designer dress,300.0,3
6,7,Coffee Maker,Start your day with a perfect cup of coffee br...,80.0,4
7,8,Toaster Oven,Upgrade your kitchen with this versatile toast...,70.0,4
8,9,Action Camera,Capture your adventures in stunning detail wit...,200.0,5
9,10,Board Game Collection,Enjoy hours of fun with this diverse collectio...,50.0,5

In [19]:
review_data_test = """
SELECT *
FROM review_data
LIMIT 10;
"""

pd.read_sql_query(review_data_test, conn)

,review_id,user_id,product_id,rating,review_text,review_date
0,1,1,1,5,Great product!,2021-01-05
1,2,2,2,4,Good product.,2021-02-10
2,3,3,3,3,Average product.,2021-03-15
3,4,4,4,5,Excellent product!,2021-04-20
4,5,5,5,2,Disappointing product.,2021-05-25
5,6,6,6,4,Good value for money.,2021-06-30
6,7,7,7,5,Highly recommended!,2021-07-05
7,8,8,8,3,Could be better.,2021-08-10
8,9,9,9,4,Satisfied with the purchase.,2021-09-15
9,10,10,10,1,Worst product ever.,2021-10-20

In [20]:
shipping_data_test = """
SELECT *
FROM shipping_data
LIMIT 10;
"""

pd.read_sql_query(shipping_data_test, conn)

   shipping_id  order_id shipping_date shipping_address tracking_number
0            1         1    2021-01-03      123 Main St          ABC123
1            2         2    2021-02-03       456 Elm St          XYZ789
2            3         3    2021-03-03       789 Oak St          DEF456
3            4         4    2021-04-03      321 Pine St          GHI789
4            5         5    2021-05-03     654 Maple St          JKL012
5            6         6    2021-06-03     987 Cedar St          MNO345
6            7         7    2021-07-03     210 Birch St          PQR678
7            8         8    2021-08-03    543 Walnut St          STU901
8            9         9    2021-09-03       876 Oak St          VWX234
9           10        10    2021-10-03      109 Pine St          YZ0123

## Primary keys
Categories.category_id

Products.product_id

Users.user_id

Orders.order_id

Order_Items.order_item_id

Reviews.review_id

Cart.cart_id

Cart_Items.cart_item_id

Payments.payment_id

Shipping.shipping_id

## Foreign keys and join paths
Products.category_id       → Categories.category_id

Orders.user_id             → Users.user_id

Order_Items.order_id       → Orders.order_id

Order_Items.product_id     → Products.product_id

Reviews.user_id            → Users.user_id

Reviews.product_id         → Products.product_id

Cart.user_id               → Users.user_id

Cart_Items.cart_id         → Cart.cart_id

Cart_Items.product_id      → Products.product_id

Payments.order_id          → Orders.order_id

Shipping.order_id          → Orders.order_id